"use client";

import { useEffect, useState } from "react";
import { AuthRequired } from "@/components/auth/AuthRequired";
import Header from "@/components/layout/Header";
type Settings = { voiceGuidance: boolean; vibration: boolean; displayMode: "camera" | "map" | "simple" };
const initial: Settings = { voiceGuidance: true, vibration: true, displayMode: "camera" };
function MySettings() { const [settings, setSettings] = useState<Settings>(initial); const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => { fetch("/api/settings", { cache: "no-store" }).then((response) => response.json()).then((data: { navigationSettings?: Settings }) => { if (data.navigationSettings) setSettings(data.navigationSettings); setReady(true); }).catch(() => setReady(true)); }, []); const save = async () => { setSaving(true); try { await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ navigationSettings: settings }) }); } finally { setSaving(false); } }; return <main className="my-page"><Header /><section className="my-content my-settings"><p className="landing-eyebrow"><span /> SETTINGS</p><h1>러닝 설정</h1>{!ready ? <p className="my-loading">설정을 불러오고 있습니다...</p> : <><label><span>음성 안내</span><input type="checkbox" checked={settings.voiceGuidance} onChange={(event) => setSettings({ ...settings, voiceGuidance: event.target.checked })} /></label><label><span>진동 안내</span><input type="checkbox" checked={settings.vibration} onChange={(event) => setSettings({ ...settings, vibration: event.target.checked })} /></label><fieldset><legend>기본 표시 모드</legend>{(["camera", "map", "simple"] as const).map((mode) => <button key={mode} type="button" className={settings.displayMode === mode ? "is-active" : ""} onClick={() => setSettings({ ...settings, displayMode: mode })}>{mode.toUpperCase()}</button>)}</fieldset><button className="my-save" type="button" onClick={save} disabled={saving}>{saving ? "저장 중..." : "설정 저장"}</button></>}</section></main>; }
export default function MySettingsPage() { return <AuthRequired><MySettings /></AuthRequired>; }
